### ISSUE TITLE
Show age of actors in actor profile view

### ISSUE THREAD

**Issue by mikevallano** [mikevallano/tmdb-moviequeue#138]
We show the actor's date of birth, but not age. 

It might also be cool to show the person's age for each movie, but that might also be overkill in the view.

**Comment by lortza** [comment]
This feature is WIP.

- [ ] Write tests for MoviePersonProfile class

- [x] Refactor age and minute count display into Time helper

- [x] Write tests for new Time helper & update tests for movie_helper

- [x] Remove unused instance variables in the tmdb_handler 

- [x] Rename @person_bio to @person_profile across views, controllers, and models
