### ISSUE TITLE
Movie person age does not account for death

### ISSUE THREAD

**Issue by lortza** [mikevallano/tmdb-moviequeue#145]
The age on the movie person bio does an age calculation, but does not account for whether this person is still alive. 

<img width="324" alt="screenshot 2018-09-16 19 01 15" src="https://user-images.githubusercontent.com/8680712/45602515-6d778980-b9e5-11e8-8689-7eca8663074c.png">

**Comment by mikevallano** [comment]
the api returns `deathday` in the bio response.

`null`

```
{
    "birthday": "1963-12-18",
    "known_for_department": "Acting",
    "deathday": null,
    "id": 287,
    "name": "Brad Pitt",
```

or

```
    "birthday": "1922-06-10",
    "known_for_department": "Acting",
    "deathday": "1969-06-22",
    "id": 9066,
    "name": "Judy Garland",
```
