### ISSUE TITLE
Once images are fixed, determine ongoing schedule for rake task and schedule it Heroku

### ISSUE THREAD

**Issue by mikevallano** [mikevallano/tmdb-moviequeue#195]
We want to keep data in sync w/ TMDB, so we should decide how frequently, and in what batch size we want to do it. 

Maybe once a month?

**Comment by lortza** [comment]
Notes from our conversation yesterday:

I like the idea of once a month. We can look at our data to see what our average monthly `movies` table additions are, or we can just take a guess (60?). 

For the initial back-data, we'll query for the oldest `updated_at` with a limit of 300(?) and do that over the course of X days until that number of remaining un-updated-recently records drops below X.

**Comment by mikevallano** [comment]
Closed with #202
