### ISSUE TITLE
Upgrade heroku postgres db to 10M rows

### ISSUE THREAD

**Issue by mikevallano** [mikevallano/tmdb-moviequeue#208]
Current limit is 10K rows, and we're inching toward 8,500 rows.

It will cost an additional $9/month to upgrade to the next tier. Pricing here: https://elements.heroku.com/addons/heroku-postgresql#pricing

Then the actual steps for upgrading the DB are here: https://devcenter.heroku.com/articles/updating-heroku-postgres-databases

**Comment by lortza** [comment]
I do believe you finished this!

**Comment by mikevallano** [comment]
> I do believe you finished this!

Oh yeah. I didn't realize this was still open. Grassy!
