### ISSUE TITLE
Add link to watch movie on vudu

### ISSUE THREAD

**Issue by mikevallano** [mikevallano/tmdb-moviequeue#219]
Should we _add_ it or replace YouTube, since we very rarely (ever?) watch anything on YouTube?

**Comment by lortza** [comment]
I'd like to add it as another option. We rarely use YouTube but I like
having it as an option for when I do use it. If your concern is having
another button in that space, maybe we need to think about digferent ways
to handle that UI moving forward. However, right now, for just us, another
button is fine.
