### ISSUE TITLE
Add ability to mark watched for all list members

### ISSUE THREAD

**Issue by mikevallano** [mikevallano/tmdb-moviequeue#329]
Not sure the best way to implement this. 

It's challenging because a movie can be on multiple lists, and each list may or may not have members. 🤔 

We could probably hack it for a meantime solution.

**Comment by lortza** [comment]
What if we pass the list `id` along with any link to the movie modal or show page (where we can mark as watched)? For example if i am on the `1 Esta Noche` list when i click on the movie cover for "Guidance", we should have it in the params for when i click on the "Mark as watched/Add screening" link. From there, we can mark it for everyone on the list.

Hmmm

How about this...
On the `screenings#new` page, when i am marking it as watched, the form includes 2 new optional fields: 
- check a box to "add screening for all members of list?" 
- dropdown of `current_user`s lists
These two fields will be conditionally required -- you must do neither or both of those fields.

**Comment by mikevallano** [comment]
We discussed that it'd be complicated to add this feature, and it's not something we really need
