### ISSUE TITLE
Remaining MVP items

### ISSUE THREAD

**Issue by mikevallano** [mikevallano/tmdb-moviequeue#37]
Doobelieve these are the remaining items, in order of priority:

- [x] Homepage search form is wonky
- [x] The modal is resizing oddly
- [x] Movie show page media queries need to be fixed
- [x] Movie show page "add a review" is wonky
- [x] List Edit page form alignment is wonky
- [x] Review Edit page form alignment is wonky

**Comment by lortza** [comment]
Which edit page form?

**Comment by mikevallano** [comment]
I list edit and review edit and both were wonky.

**Comment by mikevallano** [comment]
@lortza FYI, the homepage search field is showing entered characters in white, which means you can't see what's being typed.

**Comment by lortza** [comment]
not no mo'
