### ISSUE TITLE
Undo dedupe in movies seen section 

### ISSUE THREAD

**Issue by lortza** [mikevallano/tmdb-moviequeue#404]
I have seen two different movies both with the same title "A Christmas Carol". In the movies I've seen section of Cary Elwes biography, there is only one instance of a movie titled "A Christmas Carol".

**Comment by mikevallano** [comment]
doobelive this was because we didn't have a secondary sort and we've fixed this?

**Comment by lortza** [comment]
This does appear to be fixed

<img width="464" alt="Screenshot 2024-02-18 at 10 15 34 AM" src="https://github.com/mikevallano/tmdb-moviequeue/assets/8680712/02c77831-68c5-4c3f-a1d8-64c0d05967e1">
