### ISSUE TITLE
"Write a Review" button not working

### ISSUE THREAD

**Issue by lortza** [mikevallano/tmdb-moviequeue#405]
The "Write a Review" button on the modal is not working. 

After clicking, it goes into a weird state where we're on an empty version of the list page with the modal backdrop as an overlay. You can't get out of it but clicking anything. You have to use the back button and it takes you way back to where you were before the list page.

| Button  | on click behavior|
|-----|-------|
| ![Screenshot_20231231-082831](https://github.com/mikevallano/tmdb-moviequeue/assets/8680712/1171bb2f-25e6-4144-ba4c-b62205ec2fb7) | ![Screenshot_20231231-083221](https://github.com/mikevallano/tmdb-moviequeue/assets/8680712/baf0f69b-0da5-44aa-80d4-262550904a4a) |

My guess is it is another turbo thing. We may want to check other similar buttons on the modal as well

**Comment by mikevallano** [comment]
closing this since we redid the whole modal sitch
