### ISSUE TITLE
Question: What do we do when the API doesn't have a movie?

### ISSUE THREAD

**Issue by lortza** [mikevallano/tmdb-moviequeue#52]
example: La Casa de Mi Padre with Will Ferrel

**Comment by mikevallano** [comment]
@lortza 

1. incorporating autocomplete will help a lot. the movie is in the database. if you search "Casa De Mi Padre" you find it. i guess it doesn't like "la".
2. i thought about this early on, and we are only relying on TMDB data. it's all user-driven data, so one can add a move to TMDB here: https://www.themoviedb.org/movie/new. from what i've seen, TMDB has pretty much all movies, so unless something is super rare, it will very likely be in the database already.

**Comment by lortza** [comment]
What do you think of adding that link to add a new movie somewhere on the site?

**Comment by mikevallano** [comment]
Yeah, definitely. I want to build an FAQ page and give more credit to TMDB, etc.
