### ISSUE TITLE
fix issue with trailers

### ISSUE THREAD

**Issue by mikevallano** [mikevallano/tmdb-moviequeue#63]
1. why are wrong trailers being saved?
2. reslove

**Comment by lortza** [comment]
1. My experience has been that if I add a movie that has a trailer (Blair Witch Project), then after that movie, add a movie that doesn't have a trailer in the API info (Project: Valkyrie), the trailer from most recently added movie with a trailer (Blair Witch) populates the trailer for the movie without a trailer (Valkyrie). Though this doesn't make sense to me, I have seen this pattern with 3 or 4 movies. 
2. Go for it ;)
