### ISSUE TITLE
wrong birthdays, mismatched api calls

### ISSUE THREAD

**Issue by lortza** [mikevallano/tmdb-moviequeue#79]
I noticed that Ali Wong's b-day is 1931 on our app. She is actually 33 years old. On TMDB.com she does not have a b day listed. So something is fucky.

**Comment by mikevallano** [comment]
Closed with https://github.com/mikevallano/tmdb-moviequeue/commit/1d5afacf10c1378b438d884cd5a9638b5d5e44d2
